---
format: gfm
params:
  test: false
  day: 4
title: "AOC 2025 Day `r params$day`"
---

```{r}
#| label: load-pack
library(readr)
library(dplyr)
library(tidyr)
library(stringr)
library(purrr)
```


```{r}
#| label: read-parse

dat_in <- read_lines(here::here("Inputs", glue::glue("{if_else(params$test, 'test-', '')}input-day{params$day}.txt")))

dat <- str_split(dat_in, "", simplify = TRUE) 

```

# Part 1

```{r}
#| label: part1

check_access <- function(i, j){
  if (dat[i, j]!="@"){
    FALSE
  } else{
    ir <- seq(max(i-1, 1), min(i+1, nrow(dat)))
    jr <- seq(max(j-1, 1), min(j+1, ncol(dat)))
    (sum(dat[ir, jr]=="@")-1) < 4
  }
}

datout <- matrix(NA, nrow=nrow(dat), ncol=ncol(dat))

for (idxr in 1:nrow(dat)){
  for (idxc in 1:ncol(dat)){
    datout[idxr, idxc] <- check_access(idxr, idxc)
  }
}

sum(datout, na.rm=TRUE)
```

# Part 2

```{r}
#| label: part2

remove_paper <- function(layout){
  removed <- 0
  check_access_inner <- function(i, j){
    if (layout[i, j]!="@"){
      FALSE
    } else{
      ir <- seq(max(i-1, 1), min(i+1, nrow(layout)))
      jr <- seq(max(j-1, 1), min(j+1, ncol(layout)))
      (sum(layout[ir, jr]=="@")-1) < 4
    }
  }
  for (idxr in 1:nrow(layout)){
    for (idxc in 1:ncol(layout)){
      if (check_access_inner(idxr, idxc)){
        layout[idxr, idxc] <- "x"
        removed <- removed + 1
      }
    }
  }
  return(list(newlayout=layout, removed=removed))
}

layoutcur <- dat
keepgoing <- TRUE
steps <- 0
nremoved <- 0
while (keepgoing){
  tryit <- remove_paper(layoutcur)
  if (tryit$removed > 0){
    layoutcur <- tryit$newlayout
    nremoved <- nremoved + tryit$removed
    steps <- steps + 1
  } else{
    keepgoing <- FALSE
  }
  
}

sum(layoutcur=="x")
```

