---
format: gfm
params:
  test: true
  day: 9
title: "AOC 2025 Day `r params$day`"
---

```{r}
#| label: load-pack
library(readr)
library(dplyr)
library(tidyr)
library(stringr)
library(purrr)
```

```{r}
#| label: read-parse

dat_in <- read_csv(here::here("Inputs", glue::glue("{if_else(params$test, 'test-', '')}input-day{params$day}.txt")), col_names = c("X", "Y"), col_types="ii")

dat_mat <- dat_in |>
  as.matrix()

```

# Part 1

```{r}
#| label: part-1

combos <- combn(nrow(dat_in), 2)
calc_area <- function(i){
  coords <- dat_mat[combos[,i],]
  abs(prod(coords[1,]-coords[2,]+1))
}

areas <- map_dbl(1:ncol(combos), calc_area)

max(areas)
```

# Part 2

```{r}
#| label: part-2-edge-border

# Identify red and green borders
# Red is 1, Green is 2

list_of_tiles <- list()
dat_mat <- unname(dat_mat)

priorcoord <- dat_mat[nrow(dat_mat), ]
for (i in seq_len(nrow(dat_mat))){
  curcoord <- dat_mat[i,]
  
  list_of_tiles[[length(list_of_tiles) + 1]] <- c(curcoord, 1) # red
  
  # edge between corners as green
  if (priorcoord[1]==curcoord[1]){
    fillgreen_w_corner <- seq(priorcoord[2], curcoord[2])
    fillgreen <- fillgreen_w_corner[-c(1, length(fillgreen_w_corner))]
    greentiles <- matrix(NA, ncol=3, nrow=length(fillgreen))
    greentiles[,1] <- priorcoord[1]
    greentiles[,2] <- fillgreen
    greentiles[,3] <- 2
  } else{
    fillgreen_w_corner <- seq(priorcoord[1], curcoord[1])
    fillgreen <- fillgreen_w_corner[-c(1, length(fillgreen_w_corner))]
    greentiles <- matrix(NA, ncol=3, nrow=length(fillgreen))
    greentiles[,2] <- priorcoord[2]
    greentiles[,1] <- fillgreen
    greentiles[,3] <- 2
  }
  
  list_of_tiles[[length(list_of_tiles) + 1]] <- greentiles
  
  priorcoord <- curcoord
}

tiles_locations <-  do.call(rbind, list_of_tiles)

if (params$test){
  layout <- matrix(NA, nrow=max(dat_mat[,1]), ncol=max(dat_mat[,2]))
  for (i in seq_len(nrow(tiles_locations))){
    if (tiles_locations[i, 3]==1){
      layout[tiles_locations[i,1], tiles_locations[i, 2]] <- "R"
    } else{
      layout[tiles_locations[i,1], tiles_locations[i, 2]] <- "G"
    }
    
  }
  print(layout)
}

```


```{r}
#| label: part-2-fill
# Fill in the green
list_of_tiles <- list()

for (rowi in sort(unique(tiles_locations[, 1]))){
  # tiles in that row
  colsi <- tiles_locations[tiles_locations[,1]==rowi, 2]
  fillgreen_w_corner <- seq(min(colsi), max(colsi))
  fillgreen <- setdiff(fillgreen_w_corner, colsi)
  if (length(fillgreen)>0){
    greentiles <- matrix(NA, ncol=3, nrow=length(fillgreen))
    greentiles[,1] <- rowi
    greentiles[,2] <- fillgreen
    greentiles[,3] <- 2
    list_of_tiles[[length(list_of_tiles) + 1]] <- greentiles
  }
}

tiles_locations_filler <-  do.call(rbind, list_of_tiles)

if (params$test){
    for (i in seq_len(nrow(tiles_locations_filler))){
    if (tiles_locations_filler[i, 3]==1){
      layout[tiles_locations_filler[i,1], tiles_locations_filler[i, 2]] <- "R"
    } else{
      layout[tiles_locations_filler[i,1], tiles_locations_filler[i, 2]] <- "G"
    }
    
  }
  print(layout)
}

tiles_locations_all <- rbind(tiles_locations, tiles_locations_filler) 
colnames(tiles_locations_all) <- c("x", "y", "color")
tiles_df <- tiles_locations_all |> as_tibble()

```


```{r}
#| label: part-2-area
# Calculate areas

calc_area_colored <- function(i){
  tot_area <- calc_area(i)
  coords <- dat_mat[combos[,i],]
  tiles_rect <- tiles_df |>
    filter(x %in% seq(coords[1,1], coords[2,1]), y %in% seq(coords[1, 2], coords[2, 2]))
  if (nrow(tiles_rect)==tot_area){
    return(tot_area)
  } else{
    return(NA)
  }
}

areas_colored <- map_dbl(1:ncol(combos), calc_area_colored)

max(areas_colored, na.rm=TRUE)


```

